[package]
name = "rf-tools"
version = "0.1.0"
edition = "2024"
description = "Contains equations and tools for radio-frequency tasks"
license = "BSD-3-Clause"
keywords = ["rf", "radio", "radar", "telecommunication", "dsp"]
readme = "README.md"
repository = "https://github.com/NortheLo/rf-tools.git"

[dependencies]
num-traits = "0.2.19"

[dev-dependencies]
proptest = "1.11.0"
csv = "1.4.0"